# Generated by Django 4.2.12 on 2024-05-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('final_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('final_password_order', models.TextField()),
                ('final_password_progression', models.IntegerField(default=0)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scavenger.hunt')),
                ('solved', models.ManyToManyField(related_name='+', to='scavenger.riddle')),
            ],
        ),
        migrations.AddField(
            model_name='hunt',
            name='riddles',
            field=models.ManyToManyField(related_name='hunts', to='scavenger.riddle'),
        ),
    ]
