# Generated by Django 4.2.12 on 2024-05-14 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='riddles',
            field=models.ManyToManyField(blank=True, null=True, related_name='hunts', to='scavenger.riddle'),
        ),
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosks', to='scavenger.hunt')),
            ],
        ),
    ]
