# Generated by Django 4.2.12 on 2024-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0002_alter_hunt_riddles_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
