# Generated by Django 4.2.12 on 2024-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0004_alter_team_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='state',
            field=models.TextField(default='{}'),
        ),
    ]
