# Generated by Django 4.2.12 on 2024-05-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0005_kiosk_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='solved',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='scavenger.riddle'),
        ),
    ]
