# Generated by Django 4.2.13 on 2024-05-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0006_alter_team_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams_targeting', to='scavenger.kiosk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hunt',
            name='riddles',
            field=models.ManyToManyField(blank=True, related_name='hunts', to='scavenger.riddle'),
        ),
        migrations.AlterField(
            model_name='team',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='+', to='scavenger.riddle'),
        ),
    ]
