# Generated by Django 4.2.13 on 2024-05-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0007_team_destination_alter_hunt_riddles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_targeting', to='scavenger.kiosk'),
        ),
    ]
