# Generated by Django 4.2.13 on 2024-05-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger', '0008_alter_team_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
