"""
Django settings for justcanora project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys
from pathlib import Path

import pytz
from django.core.management.utils import get_random_secret_key
from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = not os.getenv("PROD", False)
DOCKER = os.getenv("DOCKER", False)

CURRENT_ACADEMIC_YEAR = "26/27"
CURRENT_SEMESTER = 1
NEWS_DAYS = [2, 3]
ENFORCE_SEMESTER_FOR_AUTH = True

PERSONAL_SPOTIFY_PLAYLIST = "spotify:playlist:07kBXGSHyNVWmOtLV3j8B6"

# Anthropic Claude models for the aitutor app. Sonnet balances tutoring +
# assessment-scoring quality against cost/latency at classroom volume; the
# throwaway summary uses Haiku. The SDK reads ANTHROPIC_API_KEY from the env.
CLAUDE_MODEL_FOR_CHAT = "claude-sonnet-4-6"
CLAUDE_MODEL_FOR_ASSESSMENT = "claude-sonnet-4-6"
CLAUDE_MODEL_FOR_SUMMARY = "claude-haiku-4-5"

# HestiaCP student hosting (lhpscs.com). See hestia.md for the full story.
# The panel API lives on the student webserver, a separate machine from this app.
HESTIA_HOST = os.getenv("HESTIA_HOST", "167.71.163.179")
HESTIA_API_PORT = os.getenv("HESTIA_API_PORT", "8083")
# Preferred auth: a restricted API access key (v-add-access-key). Falls back to
# admin user/password if no key is configured.
HESTIA_ACCESS_KEY = os.getenv("HESTIA_ACCESS_KEY", "")
HESTIA_SECRET_KEY = os.getenv("HESTIA_SECRET_KEY", "")
HESTIA_ADMIN_USER = os.getenv("HESTIA_ADMIN_USER", "")
HESTIA_ADMIN_PASSWORD = os.getenv("HESTIA_ADMIN_PASSWORD", "")
# The panel typically serves a self-signed cert on :8083, so verification is off
# by default; set HESTIA_VERIFY_SSL=1 once a trusted cert is in place.
HESTIA_VERIFY_SSL = os.getenv("HESTIA_VERIFY_SSL", "0") in ("1", "true", "True")
HESTIA_BASE_DOMAIN = os.getenv("HESTIA_BASE_DOMAIN", "lhpscs.com")
# Connection details students paste into sftp.json. Hestia chroots each SFTP
# login to their home, so the site lives under /web/<domain>/public_html.
HESTIA_SFTP_HOST = os.getenv("HESTIA_SFTP_HOST", HESTIA_HOST)
HESTIA_SFTP_PORT = os.getenv("HESTIA_SFTP_PORT", "22")
HESTIA_STUDENT_PACKAGE = os.getenv("HESTIA_STUDENT_PACKAGE", "student_package")
HESTIA_CERT_DIR = os.getenv("HESTIA_CERT_DIR", "/root/.acme.sh/lhpscs.com_ecc/")
# Shared basic-auth prompt on personal student sites (not used for shark tank).
HESTIA_BASIC_AUTH_USER = os.getenv("HESTIA_BASIC_AUTH_USER", "mscs")
HESTIA_BASIC_AUTH_PASSWORD = os.getenv("HESTIA_BASIC_AUTH_PASSWORD", "mscs")
# Guard rail: refuse to send real commands unless explicitly enabled.
HESTIA_DRY_RUN = os.getenv("HESTIA_DRY_RUN", "1") in ("1", "true", "True")
# Shared bearer token the webserver's acme.sh reloadcmd uses to fetch the
# current wildcard-cert roster (see the ssl_roster view). Empty = endpoint off.
HESTIA_ROSTER_TOKEN = os.getenv("HESTIA_ROSTER_TOKEN", "")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if DOCKER and not DEBUG:
    key_loc = "/app/secret/secret.key"
    if not os.path.exists(key_loc):
        with open(key_loc, "w") as f:
            f.write(get_random_secret_key())
    with open(key_loc, "r") as f:
        try:
            SECRET_KEY = f.read()
        except IOError:
            SECRET_KEY = ""
elif DEBUG:
    SECRET_KEY = 'django-insecure-5x+1sy-167242m776=rdp8zy03f$y182*hj7bk9e172k7b*q2v'
else:
    SECRET_KEY = ''

ALLOWED_HOSTS = [
    'canorasclass.com',
    'tr.canora.us'
]

if DEBUG:
    ALLOWED_HOSTS.extend([
        '127.0.0.1',
        'localhost',
        "*",
    ])

BASE_URL = "http://localhost:8000" if DEBUG else "https://tr.canora.us"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'django.contrib.humanize',
    'sorl.thumbnail',
    'oauth2_provider',

    'app',
    'scavenger',
    'slides',
    'wrapped',
    'aitutor',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'oauth2_provider.backends.OAuth2Backend',
]

LOGIN_URL = "/login/"

OAUTH2_PROVIDER = {
    "PKCE_REQUIRED": False
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'app.middleware.prevent_cache.PreventCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'justcanora.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.spotify.nowplaying.context_processor',
                'aitutor.utils.context.context_processor',
            ],
        },
    },
]

if DEBUG:
    TEMPLATES[0]['APP_DIRS'] = False
    TEMPLATES[0]['OPTIONS']['debug'] = True
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        'django.template.loaders.filesystem.Loader',
        'django.template.loaders.app_directories.Loader',
    ]

WSGI_APPLICATION = 'justcanora.wsgi.application'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

CRONJOBS = [
    ('30 23 * * *', 'app.tasks.cleanup.cleanup_null'),
    ('45 23 * * *', 'app.tasks.cleanup.cleanup_playlists'),
    ('0 0 * * 0', 'app.tasks.cleanup.clear_tokens'),
]

MARKDOWNIFY = {
    "default": {
        "MARKDOWN_EXTENSIONS": [
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
        ],
        "WHITELIST_TAGS": [
            "pre",
            "code",
            "span",
            "ul",
            "ol",
            "li",
            "p",
            "strong",
            "em",
            "hr",
            "h1", "h2", "h3", "h4", "h5", "h6",
            "br",
        ],
        "WHITELIST_ATTRS": [
            "class",
        ],
        "STRIP": False,
        "TAB_LENGTH": 2,
    }
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if DOCKER:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django',
            'USER': 'django',
            'PASSWORD': 'django',
            'HOST': 'mysql',
            'PORT': '3306',
            'charset': 'utf8mb4',
            'use_unicode': True,
            'OPTIONS': {
                'charset': 'utf8mb4'
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'
EST = pytz.timezone("America/New_York")

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if DOCKER:
    STATIC_ROOT = "/app/static"
    MEDIA_ROOT = "/app/media"
else:
    MEDIA_ROOT = "media"

# sorl-thumbnail converts everything to JPEG by default, which flattens alpha —
# the cut-out agent portraits (Yzma) would gain a dark box behind them instead of
# showing the card through. Keeping the source format preserves transparency and
# lets the WebP portraits stay WebP.
THUMBNAIL_PRESERVE_FORMAT = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
