# Generated by Django 5.2.1 on 2025-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutor', '0003_agent_language_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lock_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
