# Generated by Django 5.2.1 on 2025-06-26 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutor', '0004_conversation_lock_reason'),
        ('app', '0022_alter_course_type_alter_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('na', 'N/A')], max_length=100),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_assignment_id', models.IntegerField()),
                ('prompt', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentConversation',
            fields=[
                ('conversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aitutor.conversation')),
                ('credit_awarded', models.BooleanField(default=False)),
                ('understanding_score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aitutor.assessment')),
            ],
            bases=('aitutor.conversation',),
        ),
    ]
