# Generated by Django 5.2.1 on 2025-08-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutor', '0006_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='short_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
