# Generated by Django 5.2.6 on 2025-09-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutor', '0007_assessment_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('html', 'HTML/CSS'), ('na', 'N/A')], max_length=100),
        ),
    ]
