# Generated by Django 4.2.3 on 2023-08-04 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.TextField(default='{}')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='propics')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('should_show_entire_last_name', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='requested')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_null', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='MusicSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField()),
                ('artist', models.TextField(blank=True, null=True)),
                ('for_playlist', models.BooleanField()),
                ('investigated', models.BooleanField(default=False)),
                ('spotify_uri', models.CharField(blank=True, max_length=100, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_null', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('period', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(choices=[('23/24', '2023-24')], default='23/24', max_length=100)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('advisory', 'Advisory'), ('CS1', 'App Design'), ('CS2', 'Python'), ('speech', 'Public Speaking'), ('team', 'Robotics Team'), ('other', 'Other')], default='other', max_length=100)),
                ('playlist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('students', models.ManyToManyField(related_name='courses', to='app.student')),
            ],
        ),
    ]
