# Generated by Django 4.2.1 on 2023-07-28 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('should_show_entire_last_name', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.TextField()),
                ('artist', models.TextField(blank=True, null=True)),
                ('for_playlist', models.BooleanField()),
                ('investigated', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_null', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
                ('period', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('advisory', 'Advisory'), ('CS1', 'CS 1'), ('CS2', 'CS 2'), ('speech', 'Public Speaking'), ('team', 'Robotics Team'), ('other', 'Other')], default='other', max_length=100)),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='courses', to='app.student')),
            ],
        ),
    ]
