# Generated by Django 4.2.1 on 2023-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musicsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsuggestion',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
    ]
