# Generated by Django 4.2.3 on 2023-08-18 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datacollectionquestion_datacollectionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.TextField()),
                ('rating_fields', models.TextField(default='[]')),
                ('comment_fields', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to='app.student')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.speechrubric')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='app.student')),
            ],
        ),
    ]
