# Generated by Django 4.2.1 on 2023-07-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_student_picture_picrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24')], default='23/24', max_length=100),
        ),
    ]
