# Generated by Django 4.2.5 on 2023-09-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_speechrubric_speechrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechrating',
            name='available_to_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='speechrubric',
            name='available_to_view',
            field=models.BooleanField(default=False),
        ),
    ]
