# Generated by Django 4.2.5 on 2023-12-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_speechrating_available_to_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsuggestion',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicsuggestion',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
