# Generated by Django 4.2.1 on 2023-07-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0004_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.TextField(default='{}')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
