# Generated by Django 4.2.5 on 2024-04-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_musicsuggestion_data_musicsuggestion_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebserverCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('uid', models.IntegerField(unique=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
            ],
        ),
    ]
