# Generated by Django 4.2.12 on 2024-05-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_webservercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapped2024',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.student')),
                ('num_songs', models.IntegerField(blank=True, null=True)),
                ('rank_songs', models.IntegerField(blank=True, null=True)),
                ('num_assignments', models.IntegerField(blank=True, null=True)),
                ('rank_assignments', models.IntegerField(blank=True, null=True)),
                ('num_late', models.IntegerField(blank=True, null=True)),
                ('rank_late', models.IntegerField(blank=True, null=True)),
                ('num_canvas_minutes', models.IntegerField(blank=True, null=True)),
                ('rank_canvas_minutes', models.IntegerField(blank=True, null=True)),
                ('num_canvas_clicks', models.IntegerField(blank=True, null=True)),
                ('rank_canvas_clicks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
