# Generated by Django 4.2.1 on 2023-07-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
    ]
