# Generated by Django 4.2.12 on 2024-05-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wrapped2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped2024',
            name='num_songs_rejected',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
