# Generated by Django 4.2.1 on 2023-07-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_news_is_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('advisory', 'Advisory'), ('CS1', 'App Design'), ('CS2', 'Python'),
                                            ('speech', 'Public Speaking'), ('team', 'Robotics Team'),
                                            ('other', 'Other')], default='other', max_length=100),
        ),
    ]
