# Generated by Django 4.2.13 on 2024-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_wrapped2024_num_songs_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped2024',
            name='personal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
