# Generated by Django 4.2.3 on 2023-08-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_news_options_alter_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
