# Generated by Django 4.2.12 on 2024-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wrapped2024_personal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsuggestion',
            name='investigated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
