# Generated by Django 4.2.3 on 2023-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_course_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicsuggestion',
            name='spotify_uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
