# Generated by Django 5.0.7 on 2024-07-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_musicsuggestion_investigated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2023-24')], default='24/25', max_length=100),
        ),
    ]
