# Generated by Django 5.0.9 on 2024-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_teacherwrapped2025_rename_wrapped2024_wrapped2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherwrapped2025',
            name='kulaqua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherwrapped2025',
            name='nc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherwrapped2025',
            name='new_to_ccc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherwrapped2025',
            name='personal_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
