# Generated by Django 5.0.9 on 2024-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_teacherwrapped2025_kulaqua_teacherwrapped2025_nc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservercredential',
            name='shark',
            field=models.BooleanField(default=False),
        ),
    ]
