# Generated by Django 5.0.9 on 2024-12-18 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_webservercredential_shark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherWrapped2025',
            new_name='TeacherWrapped',
        ),
        migrations.RenameModel(
            old_name='Wrapped2025',
            new_name='Wrapped',
        ),
    ]
