# Generated by Django 5.0.9 on 2024-12-18 13:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_teacherwrapped2025_teacherwrapped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherwrapped',
            name='key',
            field=models.CharField(default=app.models.generate_wrapped_key, max_length=50, unique=True),
        ),
    ]
