# Generated by Django 5.1.4 on 2024-12-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_teacherwrapped_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacollectionquestion',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='news',
            name='student',
        ),
        migrations.DeleteModel(
            name='DataCollectionAnswer',
        ),
        migrations.DeleteModel(
            name='DataCollectionQuestion',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
