# Generated by Django 5.1.4 on 2025-04-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_datacollectionquestion_courses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherWrapped',
        ),
        migrations.DeleteModel(
            name='Wrapped',
        ),
    ]
