# Generated by Django 5.2.1 on 2025-06-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_teacherwrapped_delete_wrapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_uri', models.CharField(max_length=100, unique=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
