# Generated by Django 5.2.1 on 2025-06-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_approvedsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('advisory', 'Advisory'), ('CS1', 'Web Dev'), ('CS2', 'Python'), ('APCSA', 'AP Computer Science A'), ('speech', 'Public Speaking'), ('team', 'Robotics Team'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26')], default='24/25', max_length=100),
        ),
    ]
