# Generated by Django 5.2.1 on 2025-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_course_type_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26')], default='25/26', max_length=100),
        ),
    ]
