# Generated by Django 5.2.1 on 2025-08-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_course_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['year', 'semester', 'period']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['fname', 'lname']},
        ),
    ]
