# Generated by Django 5.2.14 on 2026-08-06 20:40

from django.db import migrations, models


def backfill_username_from_directory(apps, schema_editor):
    """Old rows stored the Hestia login (email prefix) in `directory`; the
    subdomain model keeps it in `username`. Copy it across before `directory`
    is dropped so existing accounts keep their login/password pairing."""
    WebserverCredential = apps.get_model('app', 'WebserverCredential')
    for cred in WebserverCredential.objects.all():
        if cred.directory and not cred.username:
            cred.username = cred.directory.split('/')[-1]
            cred.save(update_fields=['username'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservercredential',
            name='provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webservercredential',
            name='ssl_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webservercredential',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_username_from_directory,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='webservercredential',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='webservercredential',
            name='shark',
        ),
        migrations.RemoveField(
            model_name='webservercredential',
            name='uid',
        ),
        migrations.CreateModel(
            name='SharkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('domain', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('year', models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26')], default='25/26', max_length=100)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('group_number', models.IntegerField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_installed', models.BooleanField(default=False)),
                ('members', models.ManyToManyField(blank=True, related_name='shark_projects', to='app.student')),
            ],
        ),
    ]
