# Generated by Django 5.2.14 on 2026-08-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_webservercredential_directory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26'), ('26/27', '2026-27')], default='25/26', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharkproject',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26'), ('26/27', '2026-27')], default='25/26', max_length=100),
        ),
    ]
