# Generated by Django 5.2.14 on 2026-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_course_year_alter_sharkproject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('23/24', '2023-24'), ('24/25', '2024-25'), ('25/26', '2025-26'), ('26/27', '2026-27')], default='26/27', max_length=100),
        ),
    ]
