# Generated by Django 5.1.4 on 2025-04-14 15:48

import django.db.models.deletion
import wrapped.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0020_delete_teacherwrapped_delete_wrapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWrapped',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(default=wrapped.models.generate_wrapped_key, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField()),
                ('num_announcements', models.IntegerField(blank=True, null=True)),
                ('num_assignments', models.IntegerField(blank=True, null=True)),
                ('num_graded', models.IntegerField(blank=True, null=True)),
                ('num_late', models.IntegerField(blank=True, null=True)),
                ('num_zeros', models.IntegerField(blank=True, null=True)),
                ('num_canvas_minutes', models.IntegerField(blank=True, null=True)),
                ('num_canvas_clicks', models.IntegerField(blank=True, null=True)),
                ('kulaqua', models.BooleanField(default=False)),
                ('nc', models.BooleanField(default=False)),
                ('new_to_ccc', models.BooleanField(default=False)),
                ('personal_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wrapped',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.student')),
                ('num_songs', models.IntegerField(blank=True, null=True)),
                ('rank_songs', models.IntegerField(blank=True, null=True)),
                ('num_songs_rejected', models.IntegerField(blank=True, null=True)),
                ('num_assignments', models.IntegerField(blank=True, null=True)),
                ('rank_assignments', models.IntegerField(blank=True, null=True)),
                ('num_late', models.IntegerField(blank=True, null=True)),
                ('rank_late', models.IntegerField(blank=True, null=True)),
                ('num_canvas_minutes', models.IntegerField(blank=True, null=True)),
                ('rank_canvas_minutes', models.IntegerField(blank=True, null=True)),
                ('num_canvas_clicks', models.IntegerField(blank=True, null=True)),
                ('rank_canvas_clicks', models.IntegerField(blank=True, null=True)),
                ('personal_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
