# Generated by Django 5.1.4 on 2025-04-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherwrapped',
            name='display_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
