# Generated by Django 5.1.4 on 2025-05-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0002_teacherwrapped_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='robotics',
            field=models.BooleanField(default=False),
        ),
    ]
