# Generated by Django 5.2.6 on 2026-04-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0003_wrapped_robotics'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='longest_question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrapped',
            name='num_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrapped',
            name='rank_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
