# Generated by Django 5.2.13 on 2026-04-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0005_wrapped_direct_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
