# Generated by Django 5.2.13 on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wrapped", "0006_wrapped_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="college",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
