# Generated by Django 5.2.6 on 2025-09-21 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('group', models.CharField(choices=[('1', 'Tensor Titans'), ('2', 'The Hidden Layers'), ('3', 'Overfit & Ready'), ('4', 'Cache Me If You Can')], max_length=10)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('text', models.TextField()),
                ('prompt', models.TextField()),
                ('is_ai', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('welcome', 'Welcome Screen'), ('intro', 'Instructions'), ('tf', 'True/False'), ('review', 'Question Review'), ('results', 'Final Results')], max_length=30)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gaime.question')),
            ],
        ),
    ]
