# Generated by Django 5.2.6 on 2025-09-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('title', 'Welcome Screen'), ('instructions', 'Instructions'), ('question', 'Question'), ('review', 'Answer'), ('scores', 'Leaderboard'), ('results', 'Final Results')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
