# Generated by Django 5.2.6 on 2025-09-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaime', '0002_game_teams_alter_game_state_alter_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
